name: Daily Regression Test

on:
  schedule:
    - cron: "0 1 * * *" # Run every day at 1 AM UTC
  workflow_dispatch:     # Allow manual run from GitHub UI

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - run: npx playwright install --with-deps

      - run: npx playwright test --project=chromium

      - uses: actions/upload-artifact@v4
        with:
          name: regression-report
          path: playwright-report
